#
# examine eoddata.com file changes to discover the best time
# for a daily snapshot (where "best time" means least file activity)
#
# reads file snapshot data collected every hour at 08, 28, 48 minutes
# graph by directory/exchange (i.e Names/AMEX) to show earliest/latest changes
#
library(dplyr)
library(ggplot2)
#
getRawData <- function() {
	fileName <- "raw_file.out"
	read.table(fileName, sep="\t", header=TRUE)
}
#
fileCreateFrame <- function(rawDataFrame, target) {
	tempFrame <- filter(rawDataFrame, grepl(target, normalized_name))

	createTimeSeconds <- unique(tempFrame$create_time)
	createTimeString <- as.POSIXct(createTimeSeconds, origin="1970-01-01")
	createTimeDate <- as.Date(as.POSIXct(createTimeSeconds, origin="1970-01-01"))
	createTimeOnly <- strftime(createTimeString, format="%H:%M:%S")
        createWeekDay <- weekdays(createTimeDate)

	data.frame(createTimeSeconds, createTimeString, createTimeDate, createWeekDay, createTimeOnly)
}

generateGraphic <- function(dataFrame, fileName, width, height) {
	plot <- ggplot(dataFrame, aes(x=createWeekDay, y=createTimeOnly)) + geom_point()
	ggsave(fileName, width=width, height=height, dpi=600, plot)
}

generateFundamentalGraphic <- function(rawDataFrame) {
	amexFrame <- fileCreateFrame(rawDataFrame, "Fundamentals/AMEX.txt")
	generateGraphic(amexFrame, "fundy_amex.png", 7, 7)
	cbotFrame <- fileCreateFrame(rawDataFrame, "Fundamentals/CBOT.txt")
	generateGraphic(cbotFrame, "fundy_cbot.png", 7, 7)
	cfeFrame <- fileCreateFrame(rawDataFrame, "Fundamentals/CFE.txt")
	generateGraphic(cfeFrame, "fundy_cfe.png", 7, 7)
	cmeFrame <- fileCreateFrame(rawDataFrame, "Fundamentals/CME.txt")
	generateGraphic(cmeFrame, "fundy_cme.png", 7, 7)
	comexFrame <- fileCreateFrame(rawDataFrame, "Fundamentals/COMEX.txt")
	generateGraphic(comexFrame, "fundy_comex.png", 7, 7)
	forexFrame <- fileCreateFrame(rawDataFrame, "Fundamentals/FOREX.txt")
	generateGraphic(forexFrame, "fundy_forex.png", 7, 7)
	indexFrame <- fileCreateFrame(rawDataFrame, "Fundamentals/INDEX.txt")
	generateGraphic(indexFrame, "fundy_index.png", 7, 7)
	kcbtFrame <- fileCreateFrame(rawDataFrame, "Fundamentals/KCBT.txt")
	generateGraphic(kcbtFrame, "fundy_kcbt.png", 7, 7)
	mgexFrame <- fileCreateFrame(rawDataFrame, "Fundamentals/MGEX.txt")
	generateGraphic(mgexFrame, "fundy_mgex.png", 7, 7)
	nasdaqFrame <- fileCreateFrame(rawDataFrame, "Fundamentals/NASDAQ.txt")
	generateGraphic(nasdaqFrame, "fundy_nasdaq.png", 7, 7)
	nybotFrame <- fileCreateFrame(rawDataFrame, "Fundamentals/NYBOT.txt")
	generateGraphic(nybotFrame, "fundy_nybot.png", 7, 7)
	nymexFrame <- fileCreateFrame(rawDataFrame, "Fundamentals/NYMEX.txt")
	generateGraphic(nymexFrame, "fundy_nymex.png", 7, 7)
	nyseFrame <- fileCreateFrame(rawDataFrame, "Fundamentals/NYSE.txt")
	generateGraphic(nyseFrame, "fundy_nyse.png", 7, 7)
	opraFrame <- fileCreateFrame(rawDataFrame, "Fundamentals/OPRA.txt")
	generateGraphic(opraFrame, "fundy_opra.png", 7, 7)
	tsxFrame <- fileCreateFrame(rawDataFrame, "Fundamentals/TSX.txt")
	generateGraphic(tsxFrame, "fundy_tsx.png", 7, 7)
	tsxvFrame <- fileCreateFrame(rawDataFrame, "Fundamentals/TSXV.txt")
	generateGraphic(tsxvFrame, "fundy_tsxv.png", 7, 7)
	wceFrame <- fileCreateFrame(rawDataFrame, "Fundamentals/WCE.txt")
	generateGraphic(wceFrame, "fundy_wce.png", 7, 7)
}

generateNameGraphic <- function(rawDataFrame) {
	amexFrame <- fileCreateFrame(rawDataFrame, "Names/AMEX.txt")
	generateGraphic(amexFrame, "name_amex.png", 7, 12)
	cbotFrame <- fileCreateFrame(rawDataFrame, "Names/CBOT.txt")
	generateGraphic(cbotFrame, "name_cbot.png", 7, 7)
	cfeFrame <- fileCreateFrame(rawDataFrame, "Names/CFE.txt")
	generateGraphic(cfeFrame, "name_cfe.png", 7, 7)
	cmeFrame <- fileCreateFrame(rawDataFrame, "Names/CME.txt")
	generateGraphic(cmeFrame, "name_cme.png", 7, 7)
	comexFrame <- fileCreateFrame(rawDataFrame, "Names/COMEX.txt")
	generateGraphic(comexFrame, "name_comex.png", 7, 7)
	forexFrame <- fileCreateFrame(rawDataFrame, "Names/FOREX.txt")
	generateGraphic(forexFrame, "name_forex.png", 7, 30)
	indexFrame <- fileCreateFrame(rawDataFrame, "Names/INDEX.txt")
	generateGraphic(indexFrame, "name_index.png", 7, 40)
	kcbtFrame <- fileCreateFrame(rawDataFrame, "Names/KCBT.txt")
	generateGraphic(kcbtFrame, "name_kcbt.png", 7, 7)
	mgexFrame <- fileCreateFrame(rawDataFrame, "Names/MGEX.txt")
	generateGraphic(mgexFrame, "name_mgex.png", 7, 7)
	nasdaqFrame <- fileCreateFrame(rawDataFrame, "Names/NASDAQ.txt")
	generateGraphic(nasdaqFrame, "name_nasdaq.png", 7, 12)
	nybotFrame <- fileCreateFrame(rawDataFrame, "Names/NYBOT.txt")
	generateGraphic(nybotFrame, "name_nybot.png", 7, 7)
	nymexFrame <- fileCreateFrame(rawDataFrame, "Names/NYMEX.txt")
	generateGraphic(nymexFrame, "name_nymex.png", 7, 7)
	nyseFrame <- fileCreateFrame(rawDataFrame, "Names/NYSE.txt")
	generateGraphic(nyseFrame, "name_nyse.png", 7, 20)
	opraFrame <- fileCreateFrame(rawDataFrame, "Names/OPRA.txt")
	generateGraphic(opraFrame, "name_opra.png", 7, 12)
	tsxFrame <- fileCreateFrame(rawDataFrame, "Names/TSX.txt")
	generateGraphic(tsxFrame, "name_tsx.png", 7, 7)
	tsxvFrame <- fileCreateFrame(rawDataFrame, "Names/TSXV.txt")
	generateGraphic(tsxvFrame, "name_tsxv.png", 7, 7)
	wceFrame <- fileCreateFrame(rawDataFrame, "Names/WCE.txt")
	generateGraphic(wceFrame, "name_wce.png", 7, 7)
}

generatePriceGraphic <- function(rawDataFrame) {
	amexFrame <- fileCreateFrame(rawDataFrame, "^AMEX")
	generateGraphic(amexFrame, "price_amex.png", 7, 12)
	cbotFrame <- fileCreateFrame(rawDataFrame, "^CBOT")
	generateGraphic(cbotFrame, "price_cbot.png", 7, 7)
	cfeFrame <- fileCreateFrame(rawDataFrame, "^CFE")
	generateGraphic(cfeFrame, "price_cfe.png", 7, 7)
	cmeFrame <- fileCreateFrame(rawDataFrame, "^CME")
	generateGraphic(cmeFrame, "price_cme.png", 7, 7)
	comexFrame <- fileCreateFrame(rawDataFrame, "^COMEX")
	generateGraphic(comexFrame, "price_comex.png", 7, 7)
	forexFrame <- fileCreateFrame(rawDataFrame, "^FOREX")
	generateGraphic(forexFrame, "price_forex.png", 7, 30)
	indexFrame <- fileCreateFrame(rawDataFrame, "^INDEX")
	generateGraphic(indexFrame, "price_index.png", 7, 40)
	kcbtFrame <- fileCreateFrame(rawDataFrame, "^KCBT")
	generateGraphic(kcbtFrame, "price_kcbt.png", 7, 7)
	mgexFrame <- fileCreateFrame(rawDataFrame, "^MGEX")
	generateGraphic(mgexFrame, "price_mgex.png", 7, 7)
	nasdaqFrame <- fileCreateFrame(rawDataFrame, "^NASDAQ")
	generateGraphic(nasdaqFrame, "price_nasdaq.png", 7, 12)
	nybotFrame <- fileCreateFrame(rawDataFrame, "^NYBOT")
	generateGraphic(nybotFrame, "price_nybot.png", 7, 7)
	nymexFrame <- fileCreateFrame(rawDataFrame, "^NYMEX")
	generateGraphic(nymexFrame, "price_nymex.png", 7, 7)
	nyseFrame <- fileCreateFrame(rawDataFrame, "^NYSE")
	generateGraphic(nyseFrame, "price_nyse.png", 7, 12)
	opraFrame <- fileCreateFrame(rawDataFrame, "^OPRA")
	generateGraphic(opraFrame, "price_opra.png", 7, 7)
	tsxFrame <- fileCreateFrame(rawDataFrame, "^TSX")
	generateGraphic(tsxFrame, "price_tsx.png", 7, 7)
	tsxvFrame <- fileCreateFrame(rawDataFrame, "^TSXV")
	generateGraphic(tsxvFrame, "price_tsxv.png", 7, 7)
	wceFrame <- fileCreateFrame(rawDataFrame, "^WCE")
	generateGraphic(wceFrame, "price_wce.png", 7, 7)
}

generateTechnicalGraphic <- function(rawDataFrame) {
	amexFrame <- fileCreateFrame(rawDataFrame, "Technical/AMEX.txt")
	generateGraphic(amexFrame, "tech_amex.png", 7, 7)
	cbotFrame <- fileCreateFrame(rawDataFrame, "Technical/CBOT.txt")
	generateGraphic(cbotFrame, "tech_cbot.png", 7, 7)
	cfeFrame <- fileCreateFrame(rawDataFrame, "Technical/CFE.txt")
	generateGraphic(cfeFrame, "tech_cfe.png", 7, 7)
	cmeFrame <- fileCreateFrame(rawDataFrame, "Technical/CME.txt")
	generateGraphic(cmeFrame, "tech_cme.png", 7, 7)
	comexFrame <- fileCreateFrame(rawDataFrame, "Technical/COMEX.txt")
	generateGraphic(comexFrame, "tech_comex.png", 7, 7)
	forexFrame <- fileCreateFrame(rawDataFrame, "Technical/FOREX.txt")
	generateGraphic(forexFrame, "tech_forex.png", 7, 7)
	indexFrame <- fileCreateFrame(rawDataFrame, "Technical/INDEX.txt")
	generateGraphic(indexFrame, "tech_index.png", 7, 7)
	kcbtFrame <- fileCreateFrame(rawDataFrame, "Technical/KCBT.txt")
	generateGraphic(kcbtFrame, "tech_kcbt.png", 7, 7)
	mgexFrame <- fileCreateFrame(rawDataFrame, "Technical/MGEX.txt")
	generateGraphic(mgexFrame, "tech_mgex.png", 7, 7)
	nasdaqFrame <- fileCreateFrame(rawDataFrame, "Technical/NASDAQ.txt")
	generateGraphic(nasdaqFrame, "tech_nasdaq.png", 7, 7)
	nybotFrame <- fileCreateFrame(rawDataFrame, "Technical/NYBOT.txt")
	generateGraphic(nybotFrame, "tech_nybot.png", 7, 7)
	nymexFrame <- fileCreateFrame(rawDataFrame, "Technical/NYMEX.txt")
	generateGraphic(nymexFrame, "tech_nymex.png", 7, 7)
	nyseFrame <- fileCreateFrame(rawDataFrame, "Technical/NYSE.txt")
	generateGraphic(nyseFrame, "tech_nyse.png", 7, 7)
	opraFrame <- fileCreateFrame(rawDataFrame, "Technical/OPRA.txt")
	generateGraphic(opraFrame, "tech_opra.png", 7, 7)
	tsxFrame <- fileCreateFrame(rawDataFrame, "Technical/TSX.txt")
	generateGraphic(tsxFrame, "tech_tsx.png", 7, 7)
	tsxvFrame <- fileCreateFrame(rawDataFrame, "Technical/TSXV.txt")
	generateGraphic(tsxvFrame, "tech_tsxv.png", 7, 7)
	wceFrame <- fileCreateFrame(rawDataFrame, "Technical/WCE.txt")
	generateGraphic(wceFrame, "tech_wce.png", 7, 7)
}

#
rawDataFrame <- getRawData()
#
generateFundamentalGraphic(rawDataFrame)
generateNameGraphic(rawDataFrame)
generatePriceGraphic(rawDataFrame)
generateTechnicalGraphic(rawDataFrame)
#
